export default [
  "Did you know Bulbasaur can go for days without food? They store energy in the bulb on their back! 🍃",
  "The average Ivysaur is 3 feet and 3 inches tall!",
  "The flower on the back of a Venusaur isn't just for show! Not only does it absorb sunlight, it also gives off a sweet, soothing scent! 🌸💥",
  "Did you know that the flame on the tail of a Charmander can be an indicator of its state of mind? The happier the Charmander, the brighter the flame! 🔥",
  "It is said that when Charmeleon get excited, the flame on their tail burns a bluish white color! 🔥",
  "The more battles a Charizard has experienced, the hotter its flame burns! 🔥",
  "A Squirtle's shell is not just for protection. Its rounded shape and grooves allow it to swim at high speeds! 💧",
  "The average Wartortle weighs about 50 pounds!",
  "The cannons on the back of a Blastoise are so accurate, they can hit targets over 160 feet away!",
  "Careful, Trainers! If you touch the feeler on the head of a Caterpie, it will release a horrible stench to protect itself!",
  "Did you know, Trainers? The shell covering a Metapod is as hard as an iron slab!",
  "The wings of a Butterfree repel water, enabling it to fly in the rain.",
  "Weedle eat their own body weight in leaves every day. Talk about a healthy appetite!",
  "Kakuna may only be able to move slightly, but they can still use their stinger to poison enemies! Better watch out…",
  "Beedrill are extremely territorial. Don’t approach their nest, or you could get stung!",
  "It is said Pidgey are so docile that when they're attacked, they'd rather kick up sand than fight back!",
  "Pidgeotto have outstanding vision. No matter how high they are flying, they can identify even small movements on the ground!",
  "Pidgeot can reach up to Mach 2 speed!",
  "Rattata live in very large groups. If you see one, you can be certain lots more live in the area!",
  "Did you know that Raticate are actually very good swimmers? They even have webbed hind feet!",
  "Spearow have a very loud cry that can be heard up to half a mile away!",
  "Fearow have likely been around for a long time! Drawings resembling these Pokémon can be found in murals from ancient history.",
  "You can tell the age of an Ekans by its length. The older it gets, the longer it grows!",
  "Arbok are immensely strong and can even flatten steel oil drums with their bodies!",
  "When a Pikachu encounters something new, it blasts it with a jolt of electricity—so be careful when trying to catch one!",
  "Raichu can glow in the dark due to the electricity stored in their bodies!",
  "Sandshrew can roll themselves up into a ball instantly. This way, they protect themselves from attacks with their tough hide.",
  "Should they break, the claws of a Sandslash grow back in a day!",
  "Nidoran♀ might be small, but the poison in their horns packs a serious punch! 💥",
  "Nidorina have a very gentle nature. When they are with their friends or family, they always keep the barbs on their bodies tucked away to avoid hurting anyone. 💗",
  "Watch out for Nidoqueen. Their tackles often send their foes flying!",
  "Nidoran♂ flap their ears like wings when they are listening to distant sounds!",
  "Be careful around Nidorino, Trainers! These aggressive Pokémon attack without warning when they feel anything is wrong in their surroundings!",
  "One swing of Nidoking’s mighty tail can snap a telephone pole as if it were a matchstick.",
  "The moonlight that Clefairy store in the wings on their back apparently gives them the ability to float in midair!",
  "Clefable have such good hearing, they can hear a pin drop from over half a mile away—so make sure you don’t shout around them!"
];
